### PR TITLE
Create CI/CD pipeline

### PR DESCRIPTION
**Pull request by Carl-Hugo**
Create CI/CD pipeline; see #3 for more info.

### CODE REVIEW

**Comment by Carl-Hugo** [comment]
Here are a few things we need to discuss or do before merging:

- [ ] You need to create and set a secret value under the key `NPM_TOKEN` that allows the pipeline to publish on your behalf. See [Encrypted secrets (GitHub)](https://docs.github.com/en/actions/reference/encrypted-secrets) and [Creating and viewing access tokens (NPM)](https://docs.npmjs.com/creating-and-viewing-access-tokens) for more info.
- [ ] What do you think about the build matrix (node 10, 12, 14, Ubuntu, macOS, Windows, and x64)? We can add or remove elements from there. That matrix is used to validates that the `build` and `test` scripts work on those machines (_I know that `test` is empty at the moment, but still, it is executed_).
    > Note that I have shamelessly stolen that matrix from the `actions/setup-node` sample, so don'.t give me too much credit for it 😉
- [ ] The `version` property of the `package.json` file is now useless and set at build-time by `Nerdbank.GitVersioning` (`nbgv`). The base version is now managed by the `version` property of the `version.json` file and other `nbgv` configs. So I set the `package.json` version to `0.0.0` to avoid confusion.
- [ ] To avoid conflict, I bumped minor to `1`, so versions are `0.1.[commit depth]`.

I think that's it (I'll comment on the process in another comment).

Once all of that is reviewed, settled, and possibly updated, we can merge the PR.

**Comment by Carl-Hugo** [comment]
# How it works?

There are two jobs and two triggers.

The two jobs are:

- Build and test (`build-and-test`)
- Deploy (`deploy`)

The triggers are:

- Push to main
- Open a pull request to the `main` branch

> The `main` branch should only trigger the pipeline when changes are pushed to the `scss` directory, so we won't deploy a new NPM package after fixing a typo in the README file.

## Pull Requests (PR)

When someone opens a PR to `main` or push to an open PR, the pipeline will run. This is a check to ensure everything is fine before merging into `main`. During this process, the pipeline will run the following against the `[ os, node version, architecture ]` matrix:

```bash
npm i
npm run build
npm test
```

If that succeeds, the pipeline runs the second job on `ubuntu-latest` using node 12. The `deploy` job does the following:

1. Run `nbgv` that stamp the `package.json` and set some variables that we can use later.
2. Echo the `NpmPackageVersion` number (mostly for debugging purposes but also to demo how to access those variables)

## Push to main

When a PR gets merged into main or someone push to main directly (I suggest avoiding that and always use PR instead), the same process as with PRs restart, but the `deploy` job does a little more:

1. Run `nbgv` that stamp the `package.json` and set some variables that we can use later.
2. Echo the `NpmPackageVersion` number
3. `npm install`
4. `npm run build`
5. `npm publish --access=public` to npm (using the `NPM_TOKEN` secret).
6. `npm publish` to GitHub
7. Create a GitHub release following the `v{version} Release` pattern with the tag `v{version}` pattern

# What's next?

I never published an NPM package to GitHub, nor created a release, so I don't know how it works. Based on the action documentation and my general knowledge of GitHub Actions, all should be fine. Worst case I'll have some debugging to do...

Once we merge the PR, we have to take a leap of faith and hope the deployment works as expected as I did not test it. _This is the part I hate the most about CI/CD pipelines, I think._

We could also add more complexity in the future, like publishing prerelease builds (from branches or PRs), deploy to a custom NPM repository (like feadz.io and MyGet), etc.

Any questions?

**Comment by vinorodrigues** [comment]
Sorry for the late response ... I've been hashing out that Bootstrap core fork for a PR to core.  I'm reading up on this now.

**Comment by vinorodrigues** [comment]
Hey there.

I've been trying out your code on a playground and I'm having issues with the NPM deploy step.

I've created a quick test repo and copied you code to it:
Github = [vinorodrigues/20210130_playground](https://github.com/vinorodrigues/20210130_playground)
NPM = [vinorodrigues-dhcgpgbj-playground](https://www.npmjs.com/package/vinorodrigues-dhcgpgbj-playground)

I've also set up the "Repository secrets" for "NPM_TOKEN" ...

I've given you access to that repo for you to experiment with.

1. What's the "secrets.GITHUB_TOKEN".
2. You have 2x the `run: npm publish` line ... why?
3. Also, I'm getting no output from the `run: npm publish` line ...
  a. Shouldn't we see output?
  b. And if it fails then shouldn't the step fail?

**Comment by vinorodrigues** [comment]
Also seems to be running the build on each commit - and not on each pull merge :(

**Comment by vinorodrigues** [comment]
Lets use the playground for now.  Park it here for now but continue on [vinorodrigues/20210130_playground](https://github.com/vinorodrigues/20210130_playground)

Besides ... if they accept my BS core pull then I'll kill of this work and move efforts over to core 😢 👍🏼

**Comment by Carl-Hugo** [comment]
> Besides ... if they accept my BS core pull then I'll kill off this work and move efforts over to core 😢 👍🏼

Yes, bah nothing is not lost, you have this as a base for another project, and the goal of having a dark Bootstrap will be embedded instead of on the side, which is even better.

> What's the "secrets.GITHUB_TOKEN"?

That's generated and passed to the actions by GitHub. See [About the GITHUB_TOKEN secret](https://docs.github.com/en/actions/reference/authentication-in-a-workflow#about-the-github_token-secret).


> You have 2x the run: npm publish line ... why?

Point 5 and 6 of `Push to main` above:
- npm publish --access=public to **npm** (using the NPM_TOKEN secret).
- npm publish to **GitHub**

> Also, I'm getting no output from the run: npm publish line ...

The publish only occurs during a _push to `main`_ (`if: github.event_name == 'push'`), not during the PR itself (where `github.event_name` would be equal to `'pull_request'` instead). 

> And if it fails then shouldn't the step fail?

Yes, but these are skipped; they don't fail.

> Also seems to be running the build on each commit - and not on each pull merge :(

That's the goal. Each time you push code to an open PR (one or more commits), the build and tests (none in this project) will run once to ensure that everything works as expected before emerging into the `main` branch. But you could do whatever you want with it.

> Let's use the playground for now. Park it here for now but continue on [vinorodrigues/20210130_playground](https://github.com/vinorodrigues/20210130_playground)

Well, if your code is merged into the main repo, I won't spend more time on this, but feel free to play with it as a learning experience. Feel free to poke me tho, and I may have some time/tips to share to help you out.

**Comment by vinorodrigues** [comment]
closing pipeline as BS 5.3 will introduce Darkmode making this entire project moot.

**Pull request closed without merging**
